name: CI
on: push
jobs:
  eslint:
    name: Test Repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install packages
        run: npm ci
      
      - name: Run Test
        run: npm t
